FROM python:3.12-slim

# 1. Badilisha kutoka /app kwenda /opt/airflow
WORKDIR /opt/airflow

RUN apt-get update && apt-get install -y \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install fastapi
RUN pip install -r requirements.txt

# 2. Hii itakili faili zote kwenda kwenye /opt/airflow/
COPY . .

#ENV PYTHONPATH="/opt/airflow"
CMD ["python", "ml/training/train_final_model.py"]
