FROM apache/airflow:slim-latest-python3.12

USER root

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    build-essential \
    libpq-dev \
    && apt-get clean

USER airflow

RUN pip install --no-cache-dir \
    psycopg2-binary \
    apache-airflow-providers-postgres \
    apache-airflow-providers-apache-kafka \
    pandas \
    sqlalchemy \
    scikit-learn \
    lightgbm \
    joblib \
    pyarrow
