FROM python:3.12-slim

WORKDIR /opt/airflow

# 1. Weka packages muhimu za C/C++ compiler pamoja na libgomp1 ya LightGBM/XGBoost
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    g++ \
    libpq-dev \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

# 2. Upgrade pip na zana za ujenzi
RUN pip install --no-cache-dir --upgrade pip setuptools wheel

# 3. Nakili na ku-install requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4. Nakili kodi zote kwenda /opt/airflow
COPY . .

CMD ["python", "ml/training/train_final_model.py"]
