FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    build-essential \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY backend/requirements-api.txt .

RUN python -m pip install --upgrade pip setuptools wheel \
    --default-timeout=1000

RUN python -m pip install \
    --default-timeout=10000 \
    #--no-cache-dir \
    -r requirements-api.txt

COPY . .

CMD ["python","-m","uvicorn","backend.api.main:app","--host","0.0.0.0","--port","8000"]
