FROM python:3.12-slim

WORKDIR /opt/airflow


RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    g++ \
    libpq-dev \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip setuptools wheel


COPY requirements/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Nakili kodi zote kwenda /opt/airflow
COPY . .

CMD ["python", "ml/training/train_final_model.py"]
