FROM python:3.12-slim

WORKDIR /app

# Upgrade pip na kuongeza timeout/retries kuzuia ReadTimeoutError
RUN pip install --default-timeout=300 --retries=10 --no-cache-dir --upgrade pip

# Install dependencies
COPY requirements/requirements-debe.txt /app/requirements.txt

RUN pip install \
    --no-cache-dir \
    --timeout=300 \
    --retries=10 \
    -r /app/requirements.txt

# Copy source code and scripts
COPY . /app

CMD ["python", "scripts/setup_cdc.py"]
