FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_DEFAULT_TIMEOUT=100 \
    PIP_RETRIES=10

WORKDIR /app

# Sakinisha libgomp1 pekee inayotakiwa na LightGBM C-binary
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip

COPY requirements/requirements-consumer.txt .
RUN pip install --no-cache-dir -r requirements-consumer.txt

COPY . .

ENV PYTHONPATH=/app

CMD ["python", "-m", "kafka_pipeline.consumer.realtime_consumer"]
